import 'dart:io';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:juice_oracle/engine/custom_table.dart';
import 'package:juice_oracle/state/providers.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Structural self-check of the bundled starter pack (the emitted JSON is
/// generated by build_starter_tables.py — the script is the source of truth,
/// this guards the copy that actually ships).
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  final raw = File('assets/starter_tables.json').readAsStringSync();

  test('starter pack decodes as a table pack with a usable core set', () {
    final tables = decodeTablePack(raw);
    expect(tables.length, greaterThanOrEqualTo(15));

    final ids = tables.map((t) => t.id).toSet();
    expect(ids.length, tables.length, reason: 'duplicate ids');

    for (final t in tables) {
      expect(t.id, startsWith('starter-'));
      expect(t.name.trim(), isNotEmpty);
      expect(kTableCategories, contains(t.category),
          reason: '${t.id}: category ${t.category}');
      expect(t.source, kStarterTableSource);
      expect(t.rows, isNotEmpty, reason: t.id);
      final texts = t.rows.map((r) => r.text).toList();
      expect(texts.toSet().length, texts.length,
          reason: '${t.id}: duplicate rows');
      expect(texts.any((r) => r.trim().isEmpty), isFalse,
          reason: '${t.id}: blank row');
    }
    // Broad coverage: the core set spans several library buckets.
    final cats = tables.map((t) => t.category).toSet();
    expect(cats.length, greaterThanOrEqualTo(6));
  });

  test('importing the pack via addAll keeps the library metadata', () async {
    SharedPreferences.setMockInitialValues({});
    final c = ProviderContainer();
    addTearDown(c.dispose);

    await c.read(customTablesProvider.notifier).addAll(decodeTablePack(raw));
    final saved = await c.read(customTablesProvider.future);
    expect(saved.length, greaterThanOrEqualTo(15));
    // Fresh ids, preserved metadata (the pre-#263 addAll dropped these).
    expect(saved.every((t) => !t.id.startsWith('starter-')), isTrue);
    expect(saved.every((t) => t.source == kStarterTableSource), isTrue);
    expect(saved.every((t) => kTableCategories.contains(t.category)), isTrue);
    expect(saved.any((t) => t.rows.isNotEmpty), isTrue);
  });
}
