# flutter_gemma pulls in MediaPipe, whose classes reference compile-only
# annotations and proto types that aren't packaged. R8 fails the release
# build on these missing classes; they're never used at runtime, so just
# suppress the warnings (rules generated by R8's missing_rules.txt).
-dontwarn com.google.auto.value.extension.memoized.Memoized
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate
